github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: backend
    init: |
      echo ***** Starting backend *****
      echo ***** Initial setup *****
      cd us-congress-pizza-flag-tracker
      export PIP_USER=false
      cp .env.example .env
      python3 -m venv myenv
      source myenv/bin/activate
      echo ***** Installing python *****
      pip3 install -r requirements.txt
      # Below two lines fixes:
      #   ImportError: libGL.so.1: cannot open shared object file: No such file or directory
      # Related to cv2 - can be removed if do away with cv2
      echo ***** Installing libs necessary for cv2 *****
      sudo rm -rf /var/lib/apt/lists/lock
      apt-get update
      apt-get install ffmpeg libsm6 libxext6  -y
      echo ***** flask init *****
      rm -rf migrations
      DEBUG=True FLASK_APP=app.py flask db init
      echo ***** flask migrate *****
      DEBUG=True FLASK_APP=app.py flask db migrate
      echo ***** flask upgrade *****
      DEBUG=True FLASK_APP=app.py flask db upgrade

    command: |
      cd us-congress-pizza-flag-tracker
      source myenv/bin/activate
      FLASK_APP=app.py FLASK_ENV=development flask run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000-8999
    onOpen: open-preview
