github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: intialize
    init: |
      cd us-congress-pizza-flag-tracker
      export PIP_USER=false
      cp .env.example .env
      pip3 install -r requirements.txt
      DEBUG=True FLASK_APP=app.py flask db init
      DEBUG=True FLASK_APP=app.py flask db migrate
      DEBUG=True FLASK_APP=app.py flask db upgrade

    command: FLASK_APP=app.py FLASK_ENV=development flask run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
